name: Build Image

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      version:
        default: 'false'
        description: 'Version to build'
        required: false

env:
  ENDPOINT: "rix1337/docker-myjd-api"

jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then VS="false"; else VS=${{ github.event.inputs.version }}; fi
          if [[ ${VS} == "false" ]]; then
            VERSION=$(curl -Ls https://pypi.org/pypi/myjd-api/json | jq -r .info.version)
          else
            VERSION=${VS}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"

      - name: Build and push (first attempt)
        id: firstrun
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          context: "./docker"
          push: true
          tags: |
            ${{ env.ENDPOINT }}:latest
            ${{ env.ENDPOINT }}:${{ needs.version-check.outputs.output }}
          build-args: |
            VS=${{ needs.version-check.outputs.output }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sleep before retry
        if: steps.firstrun.outcome == 'failure'
        uses: jakejarvis/wait-action@master
        with:
          time: '1m'

      - name: Build and push (retry)
        if: steps.firstrun.outcome == 'failure'
        uses: docker/build-push-action@v6
        with:
          context: "./docker"
          push: true
          tags: |
            ${{ env.ENDPOINT }}:latest
            ${{ env.ENDPOINT }}:${{ needs.version-check.outputs.output }}
          build-args: |
            VS=${{ needs.version-check.outputs.output }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
